### ISSUE TITLE
InvalidProtocolBufferException

### ISSUE THREAD

**Issue by ManfredKarrer** [vinumeris/updatefx#15]
When using v1.5 or the latest master I get the following error:
09:43:02.915 [JavaFX Application Thread] ERROR io.bitsquare.app.UpdateProcess - Update failed: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag. 
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:94)
	at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:124)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:202)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:217)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:223)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.vinumeris.updatefx.UFXProtocol$SignedUpdates.parseFrom(UFXProtocol.java:3622)
	at com.vinumeris.updatefx.Updater.downloadSignedIndex(Updater.java:92)
	at com.vinumeris.updatefx.Updater.call(Updater.java:83)
	at com.vinumeris.updatefx.Updater.call(Updater.java:33)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

v1.2 works but I need the fix for 8u40 - libpackager.dylib issue

**Comment by mikehearn** [comment]
Huh, and that's reliable? I never saw it before but it sounds like the protobuf is corrupted or truncated somehow. More context please - is it downloaded, where is it downloaded from, etc. Does the --print-index command on the tool work?

**Comment by ManfredKarrer** [comment]
Just tried it again with building latest master and example app, and all worked fine. 
Don't know why it failed the other day, will try to upgrade to latest master when building next time a binary.

**Comment by mikehearn** [comment]
OK, possibly an unclean build directory.
