### ISSUE TITLE
File Not Found for "index"

### ISSUE THREAD

**Issue by fadils** [vinumeris/updatefx#17]
```
Update error: java.io.FileNotFoundException: http://localhost:8000/index
java.io.FileNotFoundException: http://localhost:8000/index
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at com.vinumeris.updatefx.Updater.downloadSignedIndex(Updater.java:83)
	at com.vinumeris.updatefx.Updater.call(Updater.java:73)
	at com.vinumeris.updatefx.Updater.call(Updater.java:33)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

"index.html" perhaps?

**Comment by fadils** [comment]
Because I'm using a rather old version (1.2) because that's what is stated in README. Didn't experience this after changing to 1.5.

**Comment by mikehearn** [comment]
Ah, sorry about that.
