### ISSUE TITLE
java.nio.file.NoSuchFileException when running app for the first time

### ISSUE THREAD

**Issue by ricmf** [vinumeris/updatefx#20]
When running the app for the first time i get the following exception:

java.nio.file.NoSuchFileException: /home/user/.local/share/MyApp/1.jar
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.Files.readAllBytes(Files.java:3152)
    at com.vinumeris.updatefx.Updater.processDownloadedUpdates(Updater.java:187)
    at com.vinumeris.updatefx.Updater.processSignedIndex(Updater.java:121)
    at com.vinumeris.updatefx.Updater.call(Updater.java:83)
    at com.vinumeris.updatefx.Updater.call(Updater.java:33)
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ricmf** [comment]
This was apparently caused by inconsistent versioning; it's solved now.
